- name: set banner
  cisco.ios.ios_banner:
    banner: login
    multiline_delimiiter: "&"
    text: "
      ####################################
    
      # Successfully entered this system #

      ####################################  
      "

    state: present
